"use client";

import { LuckyResult } from "@/types/lucky";

type Props = {
  data: LuckyResult;
};

export default function ShareImageButton({ data }: Props) {
  async function handleShare() {
    const width = 800;
    const height = 800;

    const canvas = document.createElement("canvas");
    canvas.width = width;
    canvas.height = height;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    // Background
    ctx.fillStyle = "#fefce8"; // yellow-50
    ctx.fillRect(0, 0, width, height);

    // Title
    ctx.fillStyle = "#111827";
    ctx.font = "bold 40px sans-serif";
    ctx.fillText("เลขนำโชคของคุณ", 200, 80);

    // Main Numbers 2D
    ctx.font = "bold 60px sans-serif";
    ctx.fillStyle = "#16a34a";
    ctx.fillText(data.mainNumbers2D.join("  "), 200, 180);

    // Main Numbers 3D
    ctx.font = "bold 48px sans-serif";
    ctx.fillStyle = "#2563eb";
    ctx.fillText(data.mainNumbers3D.join("  "), 200, 260);

    // Caption
    ctx.font = "24px sans-serif";
    ctx.fillStyle = "#374151";
    wrapText(ctx, data.caption, 100, 400, 600, 30);

    // Footer
    ctx.font = "20px sans-serif";
    ctx.fillStyle = "#6b7280";
    ctx.fillText("generated by lucky-ai", 250, 750);

    const dataUrl = canvas.toDataURL("image/png");

    // Download
    const link = document.createElement("a");
    link.href = dataUrl;
    link.download = "lucky-number.png";
    link.click();
  }

  return (
    <button
      onClick={handleShare}
      className="w-full mt-4 bg-green-400 hover:bg-green-500 text-black font-semibold py-3 rounded-xl"
    >
      📸 ดาวน์โหลดรูป / แชร์
    </button>
  );
}

// helper: wrap text
function wrapText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
) {
  const words = text.split(" ");
  let line = "";

  for (let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + " ";
    const metrics = ctx.measureText(testLine);
    const testWidth = metrics.width;

    if (testWidth > maxWidth && n > 0) {
      ctx.fillText(line, x, y);
      line = words[n] + " ";
      y += lineHeight;
    } else {
      line = testLine;
    }
  }

  ctx.fillText(line, x, y);
}